# Lab 1 - Pandas Intro

In [54]:
import pandas as pd

movies_df = pd.read_csv("movie.csv")
movies_df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

## Questions

DUE SEPT 9

In [55]:
import pandas as pd
#import csv
#movies_df = pd.read_csv('movie.csv')

**0.** What is the average IMDB Score of all the movies?

In [56]:
# attribute acccess (dot notation)

average_rating = movies_df['imdb_score'].mean()
average_rating

6.4374288039056085

**1.** How many movies have "Star Wars" in the movie_title field?

In [57]:
movies_df = pd.read_csv("movie.csv")
#x = 'movie_title'
#if 'movie_title' == 'Star Wars':
#    print(x)

#movies_df['movie_title'].value_counts()
# example: data['column_name'].value_counts()


starwars = movies_df['movie_title'].str.contains('Star Wars')


starwars.sum()
#instead of using .value_counts (returns True/False) use sum

8

**2.** Which movie has the highest IMDB Score? What is that score?

In [58]:
#high_imdb = movies_df['imdb_score'].max()
#print(high_imdb)
#high_imdb = movies_df.imdb_score.max()

#or

high_imdb = movies_df.sort_values('imdb_score', ascending = False)
high_imdb

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,Color,Bob Clark,32.0,88.0,84.0,177.0,Vanessa Angel,650.0,9109322.0,Comedy|Family|Sci-Fi,...,129.0,English,Germany,PG,20000000.0,2004.0,384.0,1.9,2.35,0
2240,Color,Jason Friedberg,111.0,88.0,82.0,329.0,Tony Cox,869.0,14174654.0,Comedy,...,359.0,English,USA,PG-13,25000000.0,2008.0,624.0,1.9,1.85,0
4498,Color,A. Raven Cruz,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
1126,Color,Lawrence Kasanoff,12.0,91.0,11.0,500.0,Larry Miller,719.0,NaN,Action|Animation|Comedy|Family|Fantasy,...,66.0,English,USA,PG,65000000.0,2012.0,611.0,1.7,NaN,0
2789,Color,Jon M. Chu,84.0,115.0,209.0,41.0,Sean Kingston,569.0,73000942.0,Documentary|Music,...,233.0,English,USA,G,13000000.0,2011.0,69.0,1.6,1.85,62000

**3**. Which movie has the lowest IMDB Score? What is that score?

In [59]:
#low_imdb = movies_df['imdb_score'].min()
#low_imdb

low_imdb = movies_df.sort_values('imdb_score')
low_imdb

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2789,Color,Jon M. Chu,84.0,115.0,209.0,41.0,Sean Kingston,569.0,73000942.0,Documentary|Music,...,233.0,English,USA,G,13000000.0,2011.0,69.0,1.6,1.85,62000
1126,Color,Lawrence Kasanoff,12.0,91.0,11.0,500.0,Larry Miller,719.0,NaN,Action|Animation|Comedy|Family|Fantasy,...,66.0,English,USA,PG,65000000.0,2012.0,611.0,1.7,NaN,0
2240,Color,Jason Friedberg,111.0,88.0,82.0,329.0,Tony Cox,869.0,14174654.0,Comedy,...,359.0,English,USA,PG-13,25000000.0,2008.0,624.0,1.9,1.85,0
2266,Color,Bob Clark,32.0,88.0,84.0,177.0,Vanessa Angel,650.0,9109322.0,Comedy|Family|Sci-Fi,...,129.0,English,Germany,PG,20000000.0,2004.0,384.0,1.9,2.35,0
4498,Color,A. Raven Cruz,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,...,1.0,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,...,37.0,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,2238.0,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,4144.0,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,...,NaN,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0

**4.** For each director, how many movies have they directed (from this dataset)?

In [60]:
#directors = {}
#director_val = movies_df[(movies_df.director_name & movie_title.value_counts())]

movies_df.director_name.value_counts()

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
John Putch           1
Luca Guadagnino      1
Sam Fell             1
Dan Fogelman         1
Daniel Hsia          1
Name: director_name, Length: 2397, dtype: int64

**5.** What's the average duration of Action movies?

In [61]:
#action_average = movies_df['genres'].mean()
#action_average
#action_average == ['Action']
#----------------------------------------------------
####find average duration using .mean(),###
####of action movies ['genre'] == ['Action']###
#----------------------------------------------------

#this lists all genres
x = movies_df['genres']
x
#----------------------------------------------------
#how many movies have are action?:
action_average = movies_df['genres'].str.contains('Action').value_counts()
#dont use value counts( for this one)
action_average
#----------------------------------------------------
#average duration of ALL movies
duration = movies_df['duration'].mean()
duration
#----------------------------------------------------
#average duration of ACTION movies:



#THIS IS THE ANSWER I SWEAR VVVVVVVVVVVVVVV
movies_df[movies_df['genres'].str.contains('Action')].duration.mean()

110.67657657657658

**6.** Which PG-13 movie had the biggest budget?

In [62]:
#content_rating & budget
#x = movies_df['content_rating']== 'PG-13'
#y = movies_df['budget'].max()


#how to put this all together?????

movies_df[movies_df['content_rating'] == 'PG-13'].sort_values('budget', ascending = False)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
2294,Color,Hayao Miyazaki,174.0,134.0,6000.0,745.0,Jada Pinkett Smith,893.0,2298191.0,Adventure|Animation|Fantasy,...,570.0,Japanese,Japan,PG-13,2.400000e+09,1997.0,851.0,8.4,1.85,11000
2305,Color,Katsuhiro Ôtomo,105.0,103.0,78.0,101.0,Robin Atkin Downes,488.0,410388.0,Action|Adventure|Animation|Family|Sci-Fi|Thriller,...,79.0,Japanese,Japan,PG-13,2.127520e+09,2004.0,336.0,6.9,1.85,973
3779,Color,Carlos Saura,35.0,115.0,98.0,4.0,Juan Luis Galiardo,341.0,1687311.0,Drama|Musical,...,40.0,Spanish,Spain,PG-13,7.000000e+08,1998.0,26.0,7.2,2.00,539
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,3.000000e+08,2007.0,5000.0,7.1,2.35,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,2.637000e+08,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4679,Black and White,Stacy Peralta,86.0,91.0,147.0,5.0,Jay Adams,22.0,1293295.0,Documentary|Sport,...,88.0,English,USA,PG-13,NaN,2001.0,20.0,7.7,1.37,0
4754,Color,Jeff Nichols,85.0,92.0,337.0,22.0,Natalie Canerday,35.0,45661.0,Drama|Thriller,...,32.0,English,USA,PG-13,NaN,2007.0,32.0,7.3,2.35,773
4814,Color,Eric Bugbee,2.0,98.0,0.0,21.0,Bill Allen,52.0,NaN,Action|Drama|Sport,...,1.0,English,USA,PG-13,NaN,2015.0,36.0,7.1,NaN,197
4835,Color,Peter Chelsom,57.0,100.0,23.0,545.0,Elden Henson,1000.0,2643689.0,Comedy|Drama,...,113.0,English,USA,PG-13,NaN,1998.0,577.0,7.3,1.85,0
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660

**7.** How many movies were made in each year (title_year)?

In [67]:
#yearly_movies = movies_df[['movie_title', 'title_year']]
#yearly_movies

#How to do this pandas style? this is copied from last assignment.



movies_df['title_year'].value_counts()

2009.0    253
2014.0    243
2006.0    233
2013.0    231
2010.0    225
         ...
1932.0      1
1916.0      1
1934.0      1
1925.0      1
1920.0      1
Name: title_year, Length: 91, dtype: int64

**8.** How many movies had more than 10000 movie_facebook_likes?

In [75]:
x = movies_df[movies_df['movie_facebook_likes'] > 10000].count()
x.max()

1022


**9.** How many movies have "Tom Hanks" (as actor1, actor2, or actor3)?

In [76]:
mask = (
     (movies_df.actor_1_name == "Tom Hanks") |
     (movies_df.actor_2_name == "Tom Hanks") |
     (movies_df.actor_3_name == "Tom Hanks")
     )
#mask = movies_df.actor_1_name.isin(['Kevin Hart', 'Dwayne Johnson'])
#mask

movies_df[mask].movie_title.count()
#use count to grt a numnr( it is the #of rows lol)

28

**10.**  What are the movies and number of voted users (num_voted_users) for movies that have less than 2 faces in the poster (facenumber_in_poster)?

In [82]:
#if facenumber_in_poster < 2, list name of movie + num_voted_users
movies_df[['movie_title', 'num_voted_users']][movies_df['facenumber_in_poster'] < 2]

                                     movie_title  num_voted_users
0                                         Avatar           886204
1       Pirates of the Caribbean: At World's End           471220
2                                        Spectre           275868
3                          The Dark Knight Rises          1144337
4     Star Wars: Episode VII - The Force Awakens                8
...                                          ...              ...
4909                             The Mongol King               36
4910                                   Newlyweds             1338
4912                               The Following            73839
4913                        A Plague So Pleasant               38
4915                           My Date with Drew             4285

[3313 rows x 2 columns]

**11.** What are the directors and number of director facebook likes for movies made beteween 2000 and 2004 (inclusive) sorted in descending order of director facebook likes?

In [95]:
#made between: [2000:2004] 

movies_df[['director_name', 'director_facebook_likes', 'title_year']][
    (movies_df['title_year'] >= 2000) & (movies_df['title_year'] <= 2004)
    ]

        director_name  director_facebook_likes  title_year
31          Sam Raimi                      0.0      2004.0
91    Robert Zemeckis                      0.0      2004.0
94    Jonathan Mostow                     84.0      2003.0
100         Rob Cohen                    357.0      2001.0
111       Michael Bay                      0.0      2001.0
...               ...                      ...         ...
4899  Olivier Assayas                    107.0      2004.0
4900     Jafar Panahi                    397.0      2000.0
4903     Tadeo Garcia                      5.0      2004.0
4906    Shane Carruth                    291.0      2004.0
4915         Jon Gunn                     16.0      2004.0

[932 rows x 3 columns]

12.What are the missing values (NaN)?

In [ ]:
# movies_df.movie_facebook_likes.notna().sum()
# movies_df
#what to do: 
#   replace missing values with the average or median of that column.

movies_df.duration.isna().sum()/ len(movies_df)
movies_df.duration.fillna(movies_df.duration.median())

movies_df.loc[4].duration

nan